// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: api/proto/settings.proto

package pubsub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectSettingsCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectSettings *ProjectSettings `protobuf:"bytes,1,opt,name=project_settings,json=projectSettings,proto3" json:"project_settings,omitempty"`
}

func (x *ProjectSettingsCreated) Reset() {
	*x = ProjectSettingsCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectSettingsCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSettingsCreated) ProtoMessage() {}

func (x *ProjectSettingsCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSettingsCreated.ProtoReflect.Descriptor instead.
func (*ProjectSettingsCreated) Descriptor() ([]byte, []int) {
	return file_api_proto_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectSettingsCreated) GetProjectSettings() *ProjectSettings {
	if x != nil {
		return x.ProjectSettings
	}
	return nil
}

type ProjectSettingsUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectSettings *ProjectSettings `protobuf:"bytes,1,opt,name=project_settings,json=projectSettings,proto3" json:"project_settings,omitempty"`
}

func (x *ProjectSettingsUpdated) Reset() {
	*x = ProjectSettingsUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_settings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectSettingsUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSettingsUpdated) ProtoMessage() {}

func (x *ProjectSettingsUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_settings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSettingsUpdated.ProtoReflect.Descriptor instead.
func (*ProjectSettingsUpdated) Descriptor() ([]byte, []int) {
	return file_api_proto_settings_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectSettingsUpdated) GetProjectSettings() *ProjectSettings {
	if x != nil {
		return x.ProjectSettings
	}
	return nil
}

// ExperimentVariables represents a combination of experiment variables name that a segmenter can derrive from
type ExperimentVariables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *ExperimentVariables) Reset() {
	*x = ExperimentVariables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_settings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExperimentVariables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentVariables) ProtoMessage() {}

func (x *ExperimentVariables) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_settings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentVariables.ProtoReflect.Descriptor instead.
func (*ExperimentVariables) Descriptor() ([]byte, []int) {
	return file_api_proto_settings_proto_rawDescGZIP(), []int{2}
}

func (x *ExperimentVariables) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

// Project Segmenters which holds the list of segmenters, in priority order
// and the configured ExperimentVariables to derive the segmenter from
type Segmenters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names     []string                        `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Variables map[string]*ExperimentVariables `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Segmenters) Reset() {
	*x = Segmenters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_settings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segmenters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segmenters) ProtoMessage() {}

func (x *Segmenters) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_settings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segmenters.ProtoReflect.Descriptor instead.
func (*Segmenters) Descriptor() ([]byte, []int) {
	return file_api_proto_settings_proto_rawDescGZIP(), []int{3}
}

func (x *Segmenters) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Segmenters) GetVariables() map[string]*ExperimentVariables {
	if x != nil {
		return x.Variables
	}
	return nil
}

type ProjectSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId            int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Username             string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Passkey              string                 `protobuf:"bytes,5,opt,name=passkey,proto3" json:"passkey,omitempty"`
	EnableS2IdClustering bool                   `protobuf:"varint,6,opt,name=enable_s2id_clustering,json=enableS2idClustering,proto3" json:"enable_s2id_clustering,omitempty"`
	Segmenters           *Segmenters            `protobuf:"bytes,7,opt,name=segmenters,proto3" json:"segmenters,omitempty"`
	RandomizationKey     string                 `protobuf:"bytes,8,opt,name=randomization_key,json=randomizationKey,proto3" json:"randomization_key,omitempty"`
}

func (x *ProjectSettings) Reset() {
	*x = ProjectSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_settings_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSettings) ProtoMessage() {}

func (x *ProjectSettings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_settings_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSettings.ProtoReflect.Descriptor instead.
func (*ProjectSettings) Descriptor() ([]byte, []int) {
	return file_api_proto_settings_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectSettings) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectSettings) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectSettings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProjectSettings) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProjectSettings) GetPasskey() string {
	if x != nil {
		return x.Passkey
	}
	return ""
}

func (x *ProjectSettings) GetEnableS2IdClustering() bool {
	if x != nil {
		return x.EnableS2IdClustering
	}
	return false
}

func (x *ProjectSettings) GetSegmenters() *Segmenters {
	if x != nil {
		return x.Segmenters
	}
	return nil
}

func (x *ProjectSettings) GetRandomizationKey() string {
	if x != nil {
		return x.RandomizationKey
	}
	return ""
}

var File_api_proto_settings_proto protoreflect.FileDescriptor

var file_api_proto_settings_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x75, 0x62, 0x73,
	0x75, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x5c, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x42, 0x0a,
	0x10, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x0f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x22, 0x5c, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x10, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x0f,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22,
	0x2b, 0x0a, 0x13, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xbe, 0x01, 0x0a,
	0x0a, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x12, 0x3f, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x53, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x1a, 0x59, 0x0a, 0x0e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e, 0x45,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf3, 0x02,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x16,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x32, 0x69, 0x64, 0x5f, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x14, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x32, 0x69, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x12, 0x32, 0x0a, 0x0a, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0a, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4b, 0x65, 0x79, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_settings_proto_rawDescOnce sync.Once
	file_api_proto_settings_proto_rawDescData = file_api_proto_settings_proto_rawDesc
)

func file_api_proto_settings_proto_rawDescGZIP() []byte {
	file_api_proto_settings_proto_rawDescOnce.Do(func() {
		file_api_proto_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_settings_proto_rawDescData)
	})
	return file_api_proto_settings_proto_rawDescData
}

var file_api_proto_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_settings_proto_goTypes = []interface{}{
	(*ProjectSettingsCreated)(nil), // 0: pubsub.ProjectSettingsCreated
	(*ProjectSettingsUpdated)(nil), // 1: pubsub.ProjectSettingsUpdated
	(*ExperimentVariables)(nil),    // 2: pubsub.ExperimentVariables
	(*Segmenters)(nil),             // 3: pubsub.Segmenters
	(*ProjectSettings)(nil),        // 4: pubsub.ProjectSettings
	nil,                            // 5: pubsub.Segmenters.VariablesEntry
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_api_proto_settings_proto_depIdxs = []int32{
	4, // 0: pubsub.ProjectSettingsCreated.project_settings:type_name -> pubsub.ProjectSettings
	4, // 1: pubsub.ProjectSettingsUpdated.project_settings:type_name -> pubsub.ProjectSettings
	5, // 2: pubsub.Segmenters.variables:type_name -> pubsub.Segmenters.VariablesEntry
	6, // 3: pubsub.ProjectSettings.created_at:type_name -> google.protobuf.Timestamp
	6, // 4: pubsub.ProjectSettings.updated_at:type_name -> google.protobuf.Timestamp
	3, // 5: pubsub.ProjectSettings.segmenters:type_name -> pubsub.Segmenters
	2, // 6: pubsub.Segmenters.VariablesEntry.value:type_name -> pubsub.ExperimentVariables
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_settings_proto_init() }
func file_api_proto_settings_proto_init() {
	if File_api_proto_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectSettingsCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_settings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectSettingsUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_settings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExperimentVariables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_settings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segmenters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_settings_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_settings_proto_goTypes,
		DependencyIndexes: file_api_proto_settings_proto_depIdxs,
		MessageInfos:      file_api_proto_settings_proto_msgTypes,
	}.Build()
	File_api_proto_settings_proto = out.File
	file_api_proto_settings_proto_rawDesc = nil
	file_api_proto_settings_proto_goTypes = nil
	file_api_proto_settings_proto_depIdxs = nil
}
