// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	pubsub "github.com/gojek/xp/common/pubsub"
	mock "github.com/stretchr/testify/mock"

	segmenters "github.com/gojek/xp/common/segmenters"
)

// PubSubPublisherService is an autogenerated mock type for the PubSubPublisherService type
type PubSubPublisherService struct {
	mock.Mock
}

// PublishExperimentMessage provides a mock function with given fields: updateType, experiment
func (_m *PubSubPublisherService) PublishExperimentMessage(updateType string, experiment *pubsub.Experiment) error {
	ret := _m.Called(updateType, experiment)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *pubsub.Experiment) error); ok {
		r0 = rf(updateType, experiment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishProjectSegmenterMessage provides a mock function with given fields: updateType, segmenter, projectId
func (_m *PubSubPublisherService) PublishProjectSegmenterMessage(updateType string, segmenter *segmenters.SegmenterConfiguration, projectId int64) error {
	ret := _m.Called(updateType, segmenter, projectId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *segmenters.SegmenterConfiguration, int64) error); ok {
		r0 = rf(updateType, segmenter, projectId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishProjectSettingsMessage provides a mock function with given fields: updateType, settings
func (_m *PubSubPublisherService) PublishProjectSettingsMessage(updateType string, settings *pubsub.ProjectSettings) error {
	ret := _m.Called(updateType, settings)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *pubsub.ProjectSettings) error); ok {
		r0 = rf(updateType, settings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
