// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "github.com/caraml-dev/xp/management-service/models"
	pagination "github.com/caraml-dev/xp/management-service/pagination"
	mock "github.com/stretchr/testify/mock"

	services "github.com/caraml-dev/xp/management-service/services"
)

// TreatmentHistoryService is an autogenerated mock type for the TreatmentHistoryService type
type TreatmentHistoryService struct {
	mock.Mock
}

// CreateTreatmentHistory provides a mock function with given fields: _a0
func (_m *TreatmentHistoryService) CreateTreatmentHistory(_a0 *models.Treatment) (*models.TreatmentHistory, error) {
	ret := _m.Called(_a0)

	var r0 *models.TreatmentHistory
	if rf, ok := ret.Get(0).(func(*models.Treatment) *models.TreatmentHistory); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TreatmentHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Treatment) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTreatmentHistory provides a mock function with given fields: treatmentId
func (_m *TreatmentHistoryService) DeleteTreatmentHistory(treatmentId int64) error {
	ret := _m.Called(treatmentId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(treatmentId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDBRecord provides a mock function with given fields: treatmentId, version
func (_m *TreatmentHistoryService) GetDBRecord(treatmentId models.ID, version int64) (*models.TreatmentHistory, error) {
	ret := _m.Called(treatmentId, version)

	var r0 *models.TreatmentHistory
	if rf, ok := ret.Get(0).(func(models.ID, int64) *models.TreatmentHistory); ok {
		r0 = rf(treatmentId, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TreatmentHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.ID, int64) error); ok {
		r1 = rf(treatmentId, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTreatmentHistory provides a mock function with given fields: treatmentId, version
func (_m *TreatmentHistoryService) GetTreatmentHistory(treatmentId int64, version int64) (*models.TreatmentHistory, error) {
	ret := _m.Called(treatmentId, version)

	var r0 *models.TreatmentHistory
	if rf, ok := ret.Get(0).(func(int64, int64) *models.TreatmentHistory); ok {
		r0 = rf(treatmentId, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TreatmentHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(treatmentId, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTreatmentHistory provides a mock function with given fields: treatmentId, params
func (_m *TreatmentHistoryService) ListTreatmentHistory(treatmentId int64, params services.ListTreatmentHistoryParams) ([]*models.TreatmentHistory, *pagination.Paging, error) {
	ret := _m.Called(treatmentId, params)

	var r0 []*models.TreatmentHistory
	if rf, ok := ret.Get(0).(func(int64, services.ListTreatmentHistoryParams) []*models.TreatmentHistory); ok {
		r0 = rf(treatmentId, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TreatmentHistory)
		}
	}

	var r1 *pagination.Paging
	if rf, ok := ret.Get(1).(func(int64, services.ListTreatmentHistoryParams) *pagination.Paging); ok {
		r1 = rf(treatmentId, params)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*pagination.Paging)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int64, services.ListTreatmentHistoryParams) error); ok {
		r2 = rf(treatmentId, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
