// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package schema

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/pkg/errors"
)

// Defines values for ExperimentStatus.
const (
	ExperimentStatusActive ExperimentStatus = "active"

	ExperimentStatusInactive ExperimentStatus = "inactive"
)

// Defines values for ExperimentTier.
const (
	ExperimentTierDefault ExperimentTier = "default"

	ExperimentTierOverride ExperimentTier = "override"
)

// Defines values for ExperimentType.
const (
	ExperimentTypeAB ExperimentType = "A/B"

	ExperimentTypeSwitchback ExperimentType = "Switchback"
)

// Defines values for SegmentField.
const (
	SegmentFieldId SegmentField = "id"

	SegmentFieldName SegmentField = "name"
)

// Defines values for SegmenterScope.
const (
	SegmenterScopeGlobal SegmenterScope = "global"

	SegmenterScopeProject SegmenterScope = "project"
)

// Defines values for SegmenterStatus.
const (
	SegmenterStatusActive SegmenterStatus = "active"

	SegmenterStatusInactive SegmenterStatus = "inactive"
)

// Defines values for SegmenterType.
const (
	SegmenterTypeBool SegmenterType = "bool"

	SegmenterTypeInteger SegmenterType = "integer"

	SegmenterTypeReal SegmenterType = "real"

	SegmenterTypeString SegmenterType = "string"
)

// Defines values for TreatmentField.
const (
	TreatmentFieldId TreatmentField = "id"

	TreatmentFieldName TreatmentField = "name"
)

// Constraint defines model for Constraint.
type Constraint struct {
	AllowedValues []SegmenterValues `json:"allowed_values"`
	Options       *SegmenterOptions `json:"options,omitempty"`
	PreRequisites []PreRequisite    `json:"pre_requisites"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Error   string `json:"error"`
	Message string `json:"message"`
}

// Experiment defines model for Experiment.
type Experiment struct {
	CreatedAt   time.Time             `json:"created_at"`
	Description *string               `json:"description"`
	EndTime     time.Time             `json:"end_time"`
	Id          int64                 `json:"id"`
	Interval    *int32                `json:"interval"`
	Name        string                `json:"name"`
	ProjectId   int64                 `json:"project_id"`
	Segment     ExperimentSegment     `json:"segment"`
	StartTime   time.Time             `json:"start_time"`
	Status      ExperimentStatus      `json:"status"`
	Tier        ExperimentTier        `json:"tier"`
	Treatments  []ExperimentTreatment `json:"treatments"`
	Type        ExperimentType        `json:"type"`
	UpdatedAt   time.Time             `json:"updated_at"`
	UpdatedBy   string                `json:"updated_by"`
}

// ExperimentHistory defines model for ExperimentHistory.
type ExperimentHistory struct {
	CreatedAt    time.Time             `json:"created_at"`
	Description  *string               `json:"description"`
	EndTime      time.Time             `json:"end_time"`
	ExperimentId int64                 `json:"experiment_id"`
	Id           int64                 `json:"id"`
	Interval     *int32                `json:"interval"`
	Name         string                `json:"name"`
	Segment      ExperimentSegment     `json:"segment"`
	StartTime    time.Time             `json:"start_time"`
	Status       ExperimentStatus      `json:"status"`
	Tier         ExperimentTier        `json:"tier"`
	Treatments   []ExperimentTreatment `json:"treatments"`
	Type         ExperimentType        `json:"type"`
	UpdatedAt    time.Time             `json:"updated_at"`
	UpdatedBy    string                `json:"updated_by"`
	Version      int64                 `json:"version"`
}

// ExperimentSegment defines model for ExperimentSegment.
type ExperimentSegment map[string]interface{}

// ExperimentStatus defines model for ExperimentStatus.
type ExperimentStatus string

// ExperimentTier defines model for ExperimentTier.
type ExperimentTier string

// ExperimentTreatment defines model for ExperimentTreatment.
type ExperimentTreatment struct {

	// Configuration associated with the given treatment
	Configuration map[string]interface{} `json:"configuration"`

	// Name of the treatment
	Name string `json:"name"`

	// When the experiment is matched, the % traffic to be directed to the treatment.
	// Optional for Switchback Experiments.
	Traffic *int32 `json:"traffic,omitempty"`
}

// ExperimentType defines model for ExperimentType.
type ExperimentType string

// Paging defines model for Paging.
type Paging struct {

	// Number of the current page
	Page int32 `json:"page"`

	// Total number of pages
	Pages int32 `json:"pages"`

	// Total number of results matching the query criteria
	Total int32 `json:"total"`
}

// PreRequisite defines model for PreRequisite.
type PreRequisite struct {
	SegmenterName   string            `json:"segmenter_name"`
	SegmenterValues []SegmenterValues `json:"segmenter_values"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt        time.Time `json:"created_at"`
	Id               int64     `json:"id"`
	RandomizationKey string    `json:"randomization_key"`
	Segmenters       []string  `json:"segmenters"`
	UpdatedAt        time.Time `json:"updated_at"`
	Username         string    `json:"username"`
}

// ProjectSegmenters defines model for ProjectSegmenters.
type ProjectSegmenters struct {

	// List of segmenters name within Project, in priority order.
	Names []string `json:"names"`

	// Mapping of segmenter to the configured experiment variables
	Variables ProjectSegmenters_Variables `json:"variables"`
}

// Mapping of segmenter to the configured experiment variables
type ProjectSegmenters_Variables struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// ProjectSettings defines model for ProjectSettings.
type ProjectSettings struct {
	CreatedAt            time.Time         `json:"created_at"`
	EnableS2idClustering bool              `json:"enable_s2id_clustering"`
	Passkey              string            `json:"passkey"`
	ProjectId            int64             `json:"project_id"`
	RandomizationKey     string            `json:"randomization_key"`
	Segmenters           ProjectSegmenters `json:"segmenters"`

	// Object containing information to define a valid treatment schema
	TreatmentSchema *TreatmentSchema `json:"treatment_schema,omitempty"`
	UpdatedAt       time.Time        `json:"updated_at"`
	Username        string           `json:"username"`
	ValidationUrl   *string          `json:"validation_url,omitempty"`
}

// A rule that forms part of a definition of a valid treatment schema
type Rule struct {
	Name string `json:"name"`

	// A Go template expression that must return a boolean value
	Predicate string `json:"predicate"`
}

// List of rules that define a valid treatment schema
type Rules []Rule

// Segment defines model for Segment.
type Segment struct {
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        *int64             `json:"id,omitempty"`
	Name      *string            `json:"name,omitempty"`
	ProjectId *int64             `json:"project_id,omitempty"`
	Segment   *ExperimentSegment `json:"segment,omitempty"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
	UpdatedBy *string            `json:"updated_by,omitempty"`
}

// SegmentField defines model for SegmentField.
type SegmentField string

// SegmentHistory defines model for SegmentHistory.
type SegmentHistory struct {
	CreatedAt time.Time         `json:"created_at"`
	Id        int64             `json:"id"`
	Name      string            `json:"name"`
	Segment   ExperimentSegment `json:"segment"`
	SegmentId int64             `json:"segment_id"`
	UpdatedAt time.Time         `json:"updated_at"`
	UpdatedBy string            `json:"updated_by"`
	Version   int64             `json:"version"`
}

// Segmenter defines model for Segmenter.
type Segmenter struct {
	Constraints []Constraint     `json:"constraints"`
	CreatedAt   *time.Time       `json:"created_at,omitempty"`
	Description *string          `json:"description,omitempty"`
	MultiValued bool             `json:"multi_valued"`
	Name        string           `json:"name"`
	Options     SegmenterOptions `json:"options"`
	Required    bool             `json:"required"`
	Scope       *SegmenterScope  `json:"scope,omitempty"`
	Status      *SegmenterStatus `json:"status,omitempty"`

	// List of varying combination of variables in which this segmenter is can be derived from
	TreatmentRequestFields [][]string    `json:"treatment_request_fields"`
	Type                   SegmenterType `json:"type"`
	UpdatedAt              *time.Time    `json:"updated_at,omitempty"`
}

// SegmenterOptions defines model for SegmenterOptions.
type SegmenterOptions struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SegmenterScope defines model for SegmenterScope.
type SegmenterScope string

// SegmenterStatus defines model for SegmenterStatus.
type SegmenterStatus string

// SegmenterType defines model for SegmenterType.
type SegmenterType string

// SegmenterValues defines model for SegmenterValues.
type SegmenterValues interface{}

// SelectedTreatment defines model for SelectedTreatment.
type SelectedTreatment struct {
	ExperimentId   int64                 `json:"experiment_id"`
	ExperimentName string                `json:"experiment_name"`
	Treatment      SelectedTreatmentData `json:"treatment"`
}

// SelectedTreatmentData defines model for SelectedTreatmentData.
type SelectedTreatmentData struct {

	// Custom configuration associated with the given treatment
	Configuration map[string]interface{} `json:"configuration"`
	Id            *int64                 `json:"id,omitempty"`

	// Name of the treatment
	Name string `json:"name"`

	// When the experiment is matched, the % traffic to be directed to the treatment.
	// Optional for Switchback Experiments.
	Traffic *int32 `json:"traffic,omitempty"`
}

// Treatment defines model for Treatment.
type Treatment struct {
	Configuration *map[string]interface{} `json:"configuration,omitempty"`
	CreatedAt     *time.Time              `json:"created_at,omitempty"`
	Id            *int64                  `json:"id,omitempty"`
	Name          *string                 `json:"name,omitempty"`
	ProjectId     *int64                  `json:"project_id,omitempty"`
	UpdatedAt     *time.Time              `json:"updated_at,omitempty"`
	UpdatedBy     *string                 `json:"updated_by,omitempty"`
}

// TreatmentField defines model for TreatmentField.
type TreatmentField string

// TreatmentHistory defines model for TreatmentHistory.
type TreatmentHistory struct {
	Configuration map[string]interface{} `json:"configuration"`
	CreatedAt     time.Time              `json:"created_at"`
	Id            int64                  `json:"id"`
	Name          string                 `json:"name"`
	TreatmentId   int64                  `json:"treatment_id"`
	UpdatedAt     time.Time              `json:"updated_at"`
	UpdatedBy     string                 `json:"updated_by"`
	Version       int64                  `json:"version"`
}

// Object containing information to define a valid treatment schema
type TreatmentSchema struct {

	// List of rules that define a valid treatment schema
	Rules Rules `json:"rules"`
}

// Getter for additional properties for ProjectSegmenters_Variables. Returns the specified
// element and whether it was found
func (a ProjectSegmenters_Variables) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProjectSegmenters_Variables
func (a *ProjectSegmenters_Variables) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProjectSegmenters_Variables to handle AdditionalProperties
func (a *ProjectSegmenters_Variables) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProjectSegmenters_Variables to handle AdditionalProperties
func (a ProjectSegmenters_Variables) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SegmenterOptions. Returns the specified
// element and whether it was found
func (a SegmenterOptions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SegmenterOptions
func (a *SegmenterOptions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SegmenterOptions to handle AdditionalProperties
func (a *SegmenterOptions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SegmenterOptions to handle AdditionalProperties
func (a SegmenterOptions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZS4/bNhD+KwTb3tQskBY9+Ja+D203yAbpIQkMWhzZTCRSGVLeuoH/e8GH3rQkO06a",
	"BXJaeTUznMc3D47e01QVpZIgjaar91SnOyiYe/xJSW2QCWnsrxJVCWgEuHcsz9U98PWe5ZX/jzBQuIev",
	"ETK6ol/dtIJvgtSbO9gWIA3gC893TKg5lEBXlCGyg/2tSiOUXC7pNtAfE1oirBHeVUILc4ZSTxGe1Vxj",
	"jY4JdTIROF29HJ6RDD3xuuFXmzeQGivwF0SFYx+mioP9G+i1QSG3lh5q+tGbArRm2xjXQE0nu6WvZUa1",
	"+6cEFNaZERURmAG+Zu5dprCwT5QzA98aUVjBIx056BSFi4plklWes00OdGWwggg9SL52shafIHiPVkjz",
	"w/ctnZAGtoCO0AJkz/Ih+XePaXJKsQ67ZEU8QCUq6731YkW0R+scEttQBHg7XsPQnOkhbZip9BnHeXoL",
	"fgG4nO+58PYZi5OiriGLsq4jpGaOlQP/e7EoS31MaFXys3Fb82wO8+nVAUAf8B04O5x2MBjw1IKhF9om",
	"Zj1nhngEbZNuPvaM7Gk/neS/C20UHh5KrkOj+PJs+9/rw5d0f+DpntA9oA6ongXSoDj0IduK+giVIhSH",
	"XsG4WqW4a1E8RdVgD2RVWPuFZKkRe6tFeHgd8f8AVav3lEPGqtwFLjwljcz2P2oPiILPCm1QFpm7ZCa2",
	"FbK6bPWqmB1729eEaa1SYR1G7oXZEbMDshV7kKTxOo14sS4NfdF/sQKIypyQCHtrh0GWZSIdS/h7Z0/e",
	"AWlBRoQmBTPpDnjiXn1DAjsximyAcIGQWgOM6p/86JX00zPLSaaQ3N0Lk+42LH1LWkfqR68sWEflcSYJ",
	"+k4ODpnG2/OQ+3XMn9z8SBPaKhWN+FO2tU+jIJdhTB4EoCo2gHUI0grROrD0I/KsiYmTqsdinyvDciIb",
	"4Z5skURjWeclIugqNyHQQm6d/u8qwANJURhAwS4Ikj/cm0Vr62JB6l2RRr7W9V1sPdcRAa9+YxyYNNAl",
	"cnLcPjfPXWcoWjx+IJNcFeJflyPrt3CYdl3faeOaMWilFzVFDXgihgM/u4410WRqQTErezZNhOOuZ3k/",
	"MFZ4JBP/ENrYfGkPIJbS1W4hSRCcECFJiUKhMAeikAM+sg14sW/3DIWdDf0uhHPhq+jTnopxzRpWq8P9",
	"TqS+p2jIfZFuNLd13Vb5unTbSg4o9sBJhqo4S9++Kn+ysrQ1pOunujnUdRt4t8W09o6iNcCFj0vXQ5MB",
	"NkbIrb5O3oG0B671Y8HXaV5pWxV9awikG6VyYNIXcq1PJdzZt/tL8nh6ITWEf3fmXnuyOSHNAHTnya9f",
	"EWyQc8G91RXmZ16bFxWPOk6zZeRk+GPwe1blkeHgCcEqB2J2zNhxqNCkZOhylhEOmZAuy/1vZ3k7SZEQ",
	"kyRSpU5gDLhImYmq8ZsiBooyZ8bNeQja3h+8YkWlDUEwFUrCSEA0ca1tHL5IbtLu2ad8M1G+rIu0V8X5",
	"BKacsajDu2BEalbn+vEJe/LnsfP7GPurUaTDeb8KyHnv/sbH83p7TOC66hrpw6PzQRsX/7g8sp/XuqGj",
	"flgktAuH0R7h4rVA04yi9+nwnWj5WN/5thRJ/SusIsefTqrcCH8H4PGZ4CS4PuCTVBuo2Ik6VfPrrkbs",
	"naNevO5r+dptXzNDWL1Am3Vmk396Wj3YUTFVxUZIVjfA6BArdH94TZmcGlrjB8aGzoTc70CSSgO356VK",
	"vqlkahmT4SF9Lc6akS9ZRTY+vnwTGe/RYYtXI28A34lIJr107MieTOrbFuHx20xvBR4RcFcjuW4i21xt",
	"/G4hXK0nekkD0Q5/s0JstomTAoa7o0CSuGwLu9WtAwQCy6dlvWg2FErCbUZXL8foiWRz8y+/taHH106o",
	"v9ZNrCMv+cLR4TlZtUz3yGkQD3T8mRk2u9UeqtA9MI612ClnL2crbVRB0mvsaM+eOr4sc+eWueds3UfM",
	"D2Su/ySzeePIM6fzhu/0fP6ZxqHtaA90Du8Z0B3C24glo0y6eB4frndGxeXWkdpKaZiQdoYT0pvkdglq",
	"wfW9DxysFwNzl3k9co1nHZtxdN/gM0VXsspzO+6AZKWgK+pWP2an/ZvjfwEAAP//fRWOjqYmAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
