// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package schema

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/pkg/errors"
)

// Defines values for ExperimentField.
const (
	ExperimentFieldEndTime ExperimentField = "end_time"

	ExperimentFieldId ExperimentField = "id"

	ExperimentFieldName ExperimentField = "name"

	ExperimentFieldStartTime ExperimentField = "start_time"

	ExperimentFieldStatusFriendly ExperimentField = "status_friendly"

	ExperimentFieldTier ExperimentField = "tier"

	ExperimentFieldTreatments ExperimentField = "treatments"

	ExperimentFieldType ExperimentField = "type"

	ExperimentFieldUpdatedAt ExperimentField = "updated_at"
)

// Defines values for ExperimentStatus.
const (
	ExperimentStatusActive ExperimentStatus = "active"

	ExperimentStatusInactive ExperimentStatus = "inactive"
)

// Defines values for ExperimentStatusFriendly.
const (
	ExperimentStatusFriendlyCompleted ExperimentStatusFriendly = "completed"

	ExperimentStatusFriendlyDeactivated ExperimentStatusFriendly = "deactivated"

	ExperimentStatusFriendlyRunning ExperimentStatusFriendly = "running"

	ExperimentStatusFriendlyScheduled ExperimentStatusFriendly = "scheduled"
)

// Defines values for ExperimentTier.
const (
	ExperimentTierDefault ExperimentTier = "default"

	ExperimentTierOverride ExperimentTier = "override"
)

// Defines values for ExperimentType.
const (
	ExperimentTypeAB ExperimentType = "A/B"

	ExperimentTypeSwitchback ExperimentType = "Switchback"
)

// Defines values for SegmentField.
const (
	SegmentFieldId SegmentField = "id"

	SegmentFieldName SegmentField = "name"
)

// Defines values for SegmenterScope.
const (
	SegmenterScopeGlobal SegmenterScope = "global"

	SegmenterScopeProject SegmenterScope = "project"
)

// Defines values for SegmenterStatus.
const (
	SegmenterStatusActive SegmenterStatus = "active"

	SegmenterStatusInactive SegmenterStatus = "inactive"
)

// Defines values for SegmenterType.
const (
	SegmenterTypeBool SegmenterType = "bool"

	SegmenterTypeInteger SegmenterType = "integer"

	SegmenterTypeReal SegmenterType = "real"

	SegmenterTypeString SegmenterType = "string"
)

// Defines values for TreatmentField.
const (
	TreatmentFieldId TreatmentField = "id"

	TreatmentFieldName TreatmentField = "name"
)

// Constraint defines model for Constraint.
type Constraint struct {
	AllowedValues []SegmenterValues `json:"allowed_values"`
	Options       *SegmenterOptions `json:"options,omitempty"`
	PreRequisites []PreRequisite    `json:"pre_requisites"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Error   string `json:"error"`
	Message string `json:"message"`
}

// Experiment defines model for Experiment.
type Experiment struct {
	CreatedAt   time.Time         `json:"created_at"`
	Description *string           `json:"description"`
	EndTime     time.Time         `json:"end_time"`
	Id          int64             `json:"id"`
	Interval    *int32            `json:"interval"`
	Name        string            `json:"name"`
	ProjectId   int64             `json:"project_id"`
	Segment     ExperimentSegment `json:"segment"`
	StartTime   time.Time         `json:"start_time"`
	Status      ExperimentStatus  `json:"status"`

	// The user-friendly classification of experiment statuses. The categories are
	// self-explanatory. Note that the current time plays a role in the definition
	// of some of these statuses.
	StatusFriendly ExperimentStatusFriendly `json:"status_friendly"`
	Tier           ExperimentTier           `json:"tier"`
	Treatments     []ExperimentTreatment    `json:"treatments"`
	Type           ExperimentType           `json:"type"`
	UpdatedAt      time.Time                `json:"updated_at"`
	UpdatedBy      string                   `json:"updated_by"`
	Version        int64                    `json:"version"`
}

// ExperimentField defines model for ExperimentField.
type ExperimentField string

// ExperimentHistory defines model for ExperimentHistory.
type ExperimentHistory struct {
	CreatedAt    time.Time             `json:"created_at"`
	Description  *string               `json:"description"`
	EndTime      time.Time             `json:"end_time"`
	ExperimentId int64                 `json:"experiment_id"`
	Id           int64                 `json:"id"`
	Interval     *int32                `json:"interval"`
	Name         string                `json:"name"`
	Segment      ExperimentSegment     `json:"segment"`
	StartTime    time.Time             `json:"start_time"`
	Status       ExperimentStatus      `json:"status"`
	Tier         ExperimentTier        `json:"tier"`
	Treatments   []ExperimentTreatment `json:"treatments"`
	Type         ExperimentType        `json:"type"`
	UpdatedAt    time.Time             `json:"updated_at"`
	UpdatedBy    string                `json:"updated_by"`
	Version      int64                 `json:"version"`
}

// ExperimentSegment defines model for ExperimentSegment.
type ExperimentSegment map[string]interface{}

// ExperimentStatus defines model for ExperimentStatus.
type ExperimentStatus string

// The user-friendly classification of experiment statuses. The categories are
// self-explanatory. Note that the current time plays a role in the definition
// of some of these statuses.
type ExperimentStatusFriendly string

// ExperimentTier defines model for ExperimentTier.
type ExperimentTier string

// ExperimentTreatment defines model for ExperimentTreatment.
type ExperimentTreatment struct {

	// Configuration associated with the given treatment
	Configuration map[string]interface{} `json:"configuration"`

	// Name of the treatment
	Name string `json:"name"`

	// When the experiment is matched, the % traffic to be directed to the treatment.
	// Optional for Switchback Experiments.
	Traffic *int32 `json:"traffic,omitempty"`
}

// ExperimentType defines model for ExperimentType.
type ExperimentType string

// Paging defines model for Paging.
type Paging struct {

	// Number of the current page
	Page int32 `json:"page"`

	// Total number of pages
	Pages int32 `json:"pages"`

	// Total number of results matching the query criteria
	Total int32 `json:"total"`
}

// PreRequisite defines model for PreRequisite.
type PreRequisite struct {
	SegmenterName   string            `json:"segmenter_name"`
	SegmenterValues []SegmenterValues `json:"segmenter_values"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt        time.Time `json:"created_at"`
	Id               int64     `json:"id"`
	RandomizationKey string    `json:"randomization_key"`
	Segmenters       []string  `json:"segmenters"`
	UpdatedAt        time.Time `json:"updated_at"`
	Username         string    `json:"username"`
}

// ProjectSegmenters defines model for ProjectSegmenters.
type ProjectSegmenters struct {

	// List of segmenters name within Project, in priority order.
	Names []string `json:"names"`

	// Mapping of segmenter to the configured experiment variables
	Variables ProjectSegmenters_Variables `json:"variables"`
}

// Mapping of segmenter to the configured experiment variables
type ProjectSegmenters_Variables struct {
	AdditionalProperties map[string][]string `json:"-"`
}

// ProjectSettings defines model for ProjectSettings.
type ProjectSettings struct {
	CreatedAt            time.Time         `json:"created_at"`
	EnableS2idClustering bool              `json:"enable_s2id_clustering"`
	Passkey              string            `json:"passkey"`
	ProjectId            int64             `json:"project_id"`
	RandomizationKey     string            `json:"randomization_key"`
	Segmenters           ProjectSegmenters `json:"segmenters"`

	// Object containing information to define a valid treatment schema
	TreatmentSchema *TreatmentSchema `json:"treatment_schema,omitempty"`
	UpdatedAt       time.Time        `json:"updated_at"`
	Username        string           `json:"username"`
	ValidationUrl   *string          `json:"validation_url,omitempty"`
}

// A rule that forms part of a definition of a valid treatment schema
type Rule struct {
	Name string `json:"name"`

	// A Go template expression that must return a boolean value
	Predicate string `json:"predicate"`
}

// List of rules that define a valid treatment schema
type Rules []Rule

// Segment defines model for Segment.
type Segment struct {
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        *int64             `json:"id,omitempty"`
	Name      *string            `json:"name,omitempty"`
	ProjectId *int64             `json:"project_id,omitempty"`
	Segment   *ExperimentSegment `json:"segment,omitempty"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
	UpdatedBy *string            `json:"updated_by,omitempty"`
}

// SegmentField defines model for SegmentField.
type SegmentField string

// SegmentHistory defines model for SegmentHistory.
type SegmentHistory struct {
	CreatedAt time.Time         `json:"created_at"`
	Id        int64             `json:"id"`
	Name      string            `json:"name"`
	Segment   ExperimentSegment `json:"segment"`
	SegmentId int64             `json:"segment_id"`
	UpdatedAt time.Time         `json:"updated_at"`
	UpdatedBy string            `json:"updated_by"`
	Version   int64             `json:"version"`
}

// Segmenter defines model for Segmenter.
type Segmenter struct {
	Constraints []Constraint     `json:"constraints"`
	CreatedAt   *time.Time       `json:"created_at,omitempty"`
	Description *string          `json:"description,omitempty"`
	MultiValued bool             `json:"multi_valued"`
	Name        string           `json:"name"`
	Options     SegmenterOptions `json:"options"`
	Required    bool             `json:"required"`
	Scope       *SegmenterScope  `json:"scope,omitempty"`
	Status      *SegmenterStatus `json:"status,omitempty"`

	// List of varying combination of variables in which this segmenter is can be derived from
	TreatmentRequestFields [][]string    `json:"treatment_request_fields"`
	Type                   SegmenterType `json:"type"`
	UpdatedAt              *time.Time    `json:"updated_at,omitempty"`
}

// SegmenterOptions defines model for SegmenterOptions.
type SegmenterOptions struct {
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SegmenterScope defines model for SegmenterScope.
type SegmenterScope string

// SegmenterStatus defines model for SegmenterStatus.
type SegmenterStatus string

// SegmenterType defines model for SegmenterType.
type SegmenterType string

// SegmenterValues defines model for SegmenterValues.
type SegmenterValues interface{}

// SelectedTreatment defines model for SelectedTreatment.
type SelectedTreatment struct {
	ExperimentId   int64                     `json:"experiment_id"`
	ExperimentName string                    `json:"experiment_name"`
	Metadata       SelectedTreatmentMetadata `json:"metadata"`
	Treatment      SelectedTreatmentData     `json:"treatment"`
}

// SelectedTreatmentData defines model for SelectedTreatmentData.
type SelectedTreatmentData struct {

	// Custom configuration associated with the given treatment
	Configuration map[string]interface{} `json:"configuration"`
	Id            *int64                 `json:"id,omitempty"`

	// Name of the treatment
	Name string `json:"name"`

	// When the experiment is matched, the % traffic to be directed to the treatment.
	// Optional for Switchback Experiments.
	Traffic *int32 `json:"traffic,omitempty"`
}

// SelectedTreatmentMetadata defines model for SelectedTreatmentMetadata.
type SelectedTreatmentMetadata struct {
	ExperimentType    ExperimentType `json:"experiment_type"`
	ExperimentVersion int64          `json:"experiment_version"`

	// The window id since the beginning of the current version of the Switchback experiment.
	// This field will only be set for Switchback experiments and the window id starts at 0.
	SwitchbackWindowId *int64 `json:"switchback_window_id,omitempty"`
}

// Treatment defines model for Treatment.
type Treatment struct {
	Configuration *map[string]interface{} `json:"configuration,omitempty"`
	CreatedAt     *time.Time              `json:"created_at,omitempty"`
	Id            *int64                  `json:"id,omitempty"`
	Name          *string                 `json:"name,omitempty"`
	ProjectId     *int64                  `json:"project_id,omitempty"`
	UpdatedAt     *time.Time              `json:"updated_at,omitempty"`
	UpdatedBy     *string                 `json:"updated_by,omitempty"`
}

// TreatmentField defines model for TreatmentField.
type TreatmentField string

// TreatmentHistory defines model for TreatmentHistory.
type TreatmentHistory struct {
	Configuration map[string]interface{} `json:"configuration"`
	CreatedAt     time.Time              `json:"created_at"`
	Id            int64                  `json:"id"`
	Name          string                 `json:"name"`
	TreatmentId   int64                  `json:"treatment_id"`
	UpdatedAt     time.Time              `json:"updated_at"`
	UpdatedBy     string                 `json:"updated_by"`
	Version       int64                  `json:"version"`
}

// Object containing information to define a valid treatment schema
type TreatmentSchema struct {

	// List of rules that define a valid treatment schema
	Rules Rules `json:"rules"`
}

// Getter for additional properties for ProjectSegmenters_Variables. Returns the specified
// element and whether it was found
func (a ProjectSegmenters_Variables) Get(fieldName string) (value []string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProjectSegmenters_Variables
func (a *ProjectSegmenters_Variables) Set(fieldName string, value []string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string][]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProjectSegmenters_Variables to handle AdditionalProperties
func (a *ProjectSegmenters_Variables) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string][]string)
		for fieldName, fieldBuf := range object {
			var fieldVal []string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProjectSegmenters_Variables to handle AdditionalProperties
func (a ProjectSegmenters_Variables) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for SegmenterOptions. Returns the specified
// element and whether it was found
func (a SegmenterOptions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for SegmenterOptions
func (a *SegmenterOptions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for SegmenterOptions to handle AdditionalProperties
func (a *SegmenterOptions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return errors.Wrap(err, fmt.Sprintf("error unmarshaling field %s", fieldName))
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for SegmenterOptions to handle AdditionalProperties
func (a SegmenterOptions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("error marshaling '%s'", fieldName))
		}
	}
	return json.Marshal(object)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xay4/bvBH/Vwi1vSm7RVr04FuaNu2hyQbZRXrIBgYtjWwmFKkMKTv+Av/vH/jQm9bD",
	"MfJlgZxWlmaG8/xxONxvUSLzQgoQWkWrb5FKdpBT+/hSCqWRMqHNrwJlAagZ2G+Uc3mAdL2nvHRvmIbc",
	"PvwZIYtW0Z9uG8G3XurtPWxzEBrwveM7xZE+FhCtIopIj+a3LDSTYr6kO09/iqMCYY3wpWSK6QVKvUV4",
	"V3ENNTrFkZWJkEarD/014r4nPtb8cvMJEm0E/htR4tCHiUzB/PX0SiMTW0MPFf3gSw5K0W2Iq6emld3Q",
	"VzKD2n0tAJlxZkBFBKohXVP7LZOYm6copRqeaZYbwQMdU1AJMhsVwyRKzumGQ7TSWEKAHkS6trJmr8DS",
	"Di0T+h9/b+iY0LAFtIQmQfaU98n/9jyKzynWYhc0DweoQGm8t56tiHLZOpWJTSh8elteTVEv9JDSVJdq",
	"wXKOvuZcZ8hApPy4VMSris/UEQOcz//AnKu0Sbm8gqNZBdwSUjGHkMX9ni3KUJ/iqCzSxSVQ8WyOwfTZ",
	"AypfHZO5M4CfOvO6ldaqI1sgreT3idxkYSen6mQZxr4TDB9Pr2HchoaOkzrWN7aOI88rBtzWEogyN3Za",
	"C7zafsGAdk6hjjEtL3SUalnyMRCxRpX/MqUlHp8KFkKt+Hw0+sPx8+nA4S8Muz6GdVO2EXV9QKsQq4Ni",
	"C+BrHLTumyweo6pzr8Y2QRPN9kYL/zCOSL2ddfWtCyvRww5IqQCfVdBIEk6VYhlLqCEhMiONz4nzDqgb",
	"YhgTqmErkYEiFOFRKODZM/hacCqowcEb8kZqIHpHNdGGvkQ0UoyrScHpURFKUHIgTFiCFDImmFn3UciM",
	"KJmDUUDvQEGz9qMLsHMIlkIYq2N7+khLDibcJrM5aHA7nfWUicuEsx58waaQ0ZLbLPdPzXrNG7kHRJZO",
	"RaApyUATLzK2LZFWGN+Nzcv2Z0KVkgkzVpAD0zvrry3bgyB1ikaBlKtwtCv6Da09G2Jv7NBIs4wlQwn/",
	"34GLWSs7mCI51SYMsf30F+LZiZZkAyRlCIkxQMvuyjePwh3FKCeZRHJ/YDrZbWjymTSO9IEf7CUTiNF1",
	"snfIeHE+eKCsYv7i9p9RHDVKBSP+lm7N0yDIhT9z9QJQ5hvAKgRVYRTuvDVpYmylqkA5S005EbVwRzZL",
	"ojas0xIRVMm1DzQTW6v/lxLwSBJkGpDRC4LkFndmRZV1oSB1ztsDX6vqYL+eah8Arz5+6JnU0yWwctg+",
	"26Nfp4Oc3ashFanM2W+2Rtaf4Tjuuq7ThpjR6zsu6iAU4JkY9vxst/eRHbkSFLKyY9NIOO47lncDY4QH",
	"KvF/TGlTL80CxFBa7GaCeMGx2fkKZBKZPhKJKeCN6VZm+3ZPkZlG2g3W0pQ5FH3bUTGsWc1qdDjsWOL2",
	"FAXcgXStucF1g/IVdBskB2R7SEmGMl+kb1eV17QoDIa0/VRtDhVuQ9reYhp7B9Hq5YWLS9tDowHWmomt",
	"uk7dgTALrtVzlq4TXiqDim5r8KQbKTlQ4YBcqXMFt3hUdEkdj083++nfPqCsHdmUkLoBunfk10cEE2TO",
	"Umd1iXwaNDqjkFngUcVpEkbOhj+Ufu9KHmgOXhAsue+bjXMUKSjamqWtFtn9tpY3nRTxMYkDKHUmxyA1",
	"vX5Qjf9IoiEvONW2z0NQ5rDlFMtLpQmCLlEQSnxGE7u1DcMXqM2ovfY534zAl3GRcqpYn8CYM2bt8DYY",
	"AcxqndV+4J78cwyQr376PwUi7dcbGeSFGm7PddWZ2/dH57vGU+5xfmR/rtlMS30/dWmmM4Ohy8UzlHoz",
	"Cp6n/aXj/La+dVEZKP0rzG2H93Al18ydAdJwT3A2ub7jfrMJVGhFlcjp2WAt9t5Sz56NNnzNaLTuIYxe",
	"oPQ6M8U/3q0eTauYyHzDRD2bCjaxTHWb14SKsaY1vGCo6YzJYQeClApSs14ixadSJIYx7i/S1WJRj3zJ",
	"3Lb28eVj2/Ae7UeeVeb10nckknGnHFuyR4v6rsnw8Gmmc18QEHBfZXK1iWy53LjZgj9aj+wldYq2+Ot5",
	"az16HRXQnx15kthWmx9Eb21CIFA+Lut9PaGQAu6yaPVhmD2Baq5fualNdPpohbpj3cg48pLroBbPWdTK",
	"QdOUajqdwz0VX1eMbcRYLOVfVsLEPULfjvaCLQvCuRtacPGwt1Ra5iS5xsx3cRfzazg8NRw+n5tjZXTZ",
	"jVtLwJJuLI5U7Zn1gYlUHnwdD6983GfCUqKYSMA6fANbZu9S+lNpr0T1uuX/RtObR/FgdjwL/uTAOCdS",
	"8KMJrALdj1vDpwgVqRXbUklTNB80+eswqgsvCZsOtB+WUJSX3NUMmJ/IafCHnOhqRy4809V85091P2kc",
	"mj7oiZ7eOga0j27tf6fp4+XFp7j+UHCAUneW1OyHmjKLSkw4k+wESs4Y+nQTB6tx0tQISA1c41iHZpzs",
	"v7lkMlqJknPTJIOgBYtWkR0Y6p1yX06/BwAA//+59tw0KSsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
